---
- name: Tomcat deployment playbook
  hosts: servers           # Inventory hosts group / server to act on
  become: yes               # If to escalate privilege
  become_method: sudo       # Set become method

  tasks:
    - name: Install Nginx   #Installing Nginx
      apt:
        name: nginx
        state: present
    
    - name: Install MySQL   #Installing MySQL
      apt: 
        name: mysql-server
        update_cache: yes 
        cache_valid_time: 3600 
        state: present

    - name: Start the MySQL service   #Starting MySQL
      service: 
        name: mysql 
        state: started
        enabled: true

    - name: Install Default Java      #Installing Java
      apt:
        name: default-jdk
        state: present
